djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tweetapp/", include('tweetapp.urls'))
]

djangotweet/tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('', views.listtweet, name='listtweet'), # atilsamancioglu.com/tweetapp/
    path('addtweet/', views.addtweet, name='addtweet') # atilsamancioglu.com/tweetapp/addtweet
]

djangotweet/tweetapp/models.py
from django.db import models

# Create your models here.

class Tweet(models.Model):
    nickname = models.CharField(max_length=50)
    message = models.CharField(max_length=100)

    def __str__(self) :
        return f"Tweet nick: {self.nickname} message: {self.message}"
    

djangotweet/tweetapp/views.py
from django.shortcuts import render
from . import models

# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict= {"tweets": all_tweets}
    
    return render(request, 'tweetapp/listtweet.html', context=tweet_dict)

def addtweet(request):
    return render(request, 'tweetapp/addtweet.html')

djangotweet/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Tweet App</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content%}

    {% endblock %}

</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
    <div class="mb-3">
      <label for="nickname" class="form-label">Nickname</label>
      <input type="text" class="form-control" id="nickname">
    </div>
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input type="text" class="form-control" id="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </form>
{% endblock %}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{% block content %}
<ul>

    {% for tweet in tweets%}
    <li>{{tweet}}</li>
    {% endfor %}
</ul>

{% endblock %}